-- Migration: venue_contacts
-- Adds a contact table for venue reservation info (phone/viber/whatsapp/sms/instagram)
-- Venues optionally reference a contact row via contact_id (nullable).

CREATE TABLE IF NOT EXISTS "public"."venue_contacts" (
    "id" bigint NOT NULL,
    "phone_number" "text" NOT NULL,
    "is_viber" boolean DEFAULT false NOT NULL,
    "is_phone" boolean DEFAULT false NOT NULL,
    "is_sms" boolean DEFAULT false NOT NULL,
    "is_whatsapp" boolean DEFAULT false NOT NULL,
    "instagram_handle" "text",
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL
);

ALTER TABLE "public"."venue_contacts" OWNER TO "postgres";

ALTER TABLE "public"."venue_contacts" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."venue_contacts_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY "public"."venue_contacts"
    ADD CONSTRAINT "venue_contacts_pkey" PRIMARY KEY ("id");

-- Add nullable contact_id FK to venues
ALTER TABLE "public"."venues"
    ADD COLUMN IF NOT EXISTS "contact_id" bigint;

ALTER TABLE ONLY "public"."venues"
    ADD CONSTRAINT "venues_contact_id_fkey"
    FOREIGN KEY ("contact_id") REFERENCES "public"."venue_contacts"("id") ON DELETE SET NULL;

-- RLS: hosts can manage contacts for their own venues
ALTER TABLE "public"."venue_contacts" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Hosts can manage own venue contacts" ON "public"."venue_contacts"
    USING (
        EXISTS (
            SELECT 1 FROM "public"."venues"
            WHERE "venues"."contact_id" = "venue_contacts"."id"
              AND ("auth"."uid"())::"text" = "venues"."host_id"
        )
    )
    WITH CHECK (true);

CREATE POLICY "Anyone can view venue contacts" ON "public"."venue_contacts"
    FOR SELECT USING (true);

GRANT ALL ON TABLE "public"."venue_contacts" TO "anon";
GRANT ALL ON TABLE "public"."venue_contacts" TO "authenticated";
GRANT ALL ON TABLE "public"."venue_contacts" TO "service_role";

GRANT ALL ON SEQUENCE "public"."venue_contacts_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."venue_contacts_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."venue_contacts_id_seq" TO "service_role";
