-- Persist one-sided swipe decisions so matches can be created only on mutual likes.
CREATE TABLE IF NOT EXISTS public.guest_swipes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  swiper_user_id text NOT NULL REFERENCES public.guests(user_id) ON DELETE CASCADE,
  swiped_user_id text NOT NULL REFERENCES public.guests(user_id) ON DELETE CASCADE,
  event_id uuid NOT NULL REFERENCES public.events(id) ON DELETE CASCADE,
  liked boolean NOT NULL,
  created_at timestamptz NOT NULL DEFAULT timezone('utc', now()),
  updated_at timestamptz NOT NULL DEFAULT timezone('utc', now()),
  CONSTRAINT guest_swipes_different_users CHECK (swiper_user_id <> swiped_user_id),
  CONSTRAINT guest_swipes_unique UNIQUE (swiper_user_id, swiped_user_id, event_id)
);

CREATE INDEX IF NOT EXISTS guest_swipes_event_idx
  ON public.guest_swipes (event_id);

CREATE INDEX IF NOT EXISTS guest_swipes_swiper_event_idx
  ON public.guest_swipes (swiper_user_id, event_id);

CREATE INDEX IF NOT EXISTS guest_swipes_target_event_idx
  ON public.guest_swipes (swiped_user_id, event_id);
